development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: event_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: event_test
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

  it:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: event_it
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432